plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.88'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}

var build_version = mod_version
var build_id = System.getenv("BUILD_ID")
if (build_id != null) build_version = "${mod_version}+b${build_id}"

version = "v${build_version}-mc${minecraft_version}"
group = mod_group_id

allprojects {
    repositories {
        mavenLocal()
        maven { url = "https://maven.blamejared.com/" }
        maven { url = "https://maven.terraformersmc.com/" }
        maven { url = "https://modmaven.dev" }
        maven { url = "https://cursemaven.com" }
        maven { url = "https://maven.shedaniel.me/" }
        // Registrate
        maven { url = "https://maven.ithundxr.dev/snapshots" }

        flatDir {
            dir rootProject.file('libs')
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

evaluationDependsOn(':core')
evaluationDependsOn(':datagen')
evaluationDependsOn(':compat-yf')
evaluationDependsOn(':compat-yh')

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    addModdingDependenciesTo(project(':core').sourceSets.main)
    addModdingDependenciesTo(project(':datagen').sourceSets.main)
    addModdingDependenciesTo(project(':compat-yf').sourceSets.main)
    addModdingDependenciesTo(project(':compat-yh').sourceSets.main)

    runs {
        client {
            client()
            sourceSet = project(':core').sourceSets.main
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            sourceSet = project(':core').sourceSets.main
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            sourceSet = project(':core').sourceSets.main
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            sourceSet = project(':datagen').sourceSets.main
            programArguments.addAll '--mod', project.mod_id, '--all',
                    '--output', project(':core').file('src/generated/resources/').absolutePath,
                    '--existing', project(':core').file('src/main/resources/').absolutePath
        }

        dataYF {
            data()
            sourceSet = project(':compat-yf').sourceSets.main
            programArguments.addAll '--mod', project.mod_id, '--all',
                    '--output', project(':compat-yf').file('src/generated/resources/').absolutePath,
                    '--existing', project(':core').file('src/main/resources/').absolutePath,
                    '--existing', project(':compat-yf').file('src/main/resources/').absolutePath
        }

        dataYH {
            data()
            sourceSet = project(':compat-yh').sourceSets.main
            programArguments.addAll '--mod', project.mod_id, '--all',
                    '--output', project(':compat-yh').file('src/generated/resources/').absolutePath,
                    '--existing', project(':core').file('src/main/resources/').absolutePath,
                    '--existing', project(':compat-yh').file('src/main/resources/').absolutePath
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet project(':core').sourceSets.main
            sourceSet project(':datagen').sourceSets.main
            sourceSet project(':compat-yf').sourceSets.main
            sourceSet project(':compat-yh').sourceSets.main
        }
    }
}

// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask project(':core').tasks.named('generateModMetadata')

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation project(':core')
    implementation project(':compat-yf')
    implementation project(':compat-yh')
}

def langRelPath = "assets/${mod_id}/lang/en_us.json"
def mergeLangFilesTask = tasks.register('mergeLangFiles', MergeLangTask) {
    sources.from(
            project(':core').file("src/generated/resources/${langRelPath}"),
            project(':compat-yf').file("src/generated/resources/${langRelPath}"),
            project(':compat-yh').file("src/generated/resources/${langRelPath}")
    )
    outputFile = project(':core').layout.projectDirectory.file("src/main/resources/${langRelPath}")
    outputs.upToDateWhen { false }
}

tasks.named('processResources', ProcessResources).configure {
    dependsOn mergeLangFilesTask
    from project(':core').sourceSets.main.resources
    from(project(':compat-yf').sourceSets.main.resources) {
        exclude '**/lang/en_us.json'
    }
    from(project(':compat-yh').sourceSets.main.resources) {
        exclude '**/lang/en_us.json'
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude '.cache'
    exclude 'assets/ccw/unused'
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn mergeLangFilesTask
    dependsOn ':core:classes'
    dependsOn ':compat-yf:classes'
    dependsOn ':compat-yh:classes'
    from project(':core').sourceSets.main.output
    from(project(':compat-yf').sourceSets.main.output) {
        exclude '**/lang/en_us.json'
    }
    from(project(':compat-yh').sourceSets.main.output) {
        exclude '**/lang/en_us.json'
    }
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
