name: Build
on:
  push:
    paths:
      - .github/workflows/**
      - src/**
      - gradle/**
      - build.gradle
      - gradle.properties
      - settings.gradle
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BUILD_ID: ${{ github.run_number }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.1

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Read Properties
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: "mod_id mod_name"

      - name: Get Version
        id: version
        run: |
          VERSION=$(./gradlew properties -q | grep "mod_version:" | awk '{print $2}')
          echo $(./gradlew properties -q | grep "mod_version:")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          printf '%s' "mod_version: 1.0.0" | xxd 
          printf '%s' "$VERSION" | xxd 

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.version.outputs.version }}+b${{ github.run_number }}"
          path: build/libs/*.jar