name: Build
on:
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - gradle/**
      - build.gradle
      - gradle.properties
      - settings.gradle
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BUILD_ID: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.1

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Read Properties
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: "minecraft_version mod_id mod_name mod_version"

      - name: Concatenate Mod Version
        id: version
        run: |
          echo "version=mc${{ steps.properties.outputs.minecraft_version }}-${{ steps.properties.outputs.mod_version }}" >> $GITHUB_OUTPUT

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.version.outputs.version }}+b${{ github.run_number }}"
          path: build/libs/*.jar