on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.1

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Read Properties
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: "java_version minecraft_version mod_id mod_name mod_version"

      - name: Concatenate Mod Version
        id: version
        run: |
          echo "version=v${{ steps.properties.outputs.mod_version }}-mc${{ steps.properties.outputs.minecraft_version }}" >> $GITHUB_OUTPUT

      - name: Publish To Third Party
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.version.outputs.version }}"
          version: ${{ steps.version.outputs.version }}
          version-type: release
          github-tag: ${{ steps.version.outputs.version }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: build/libs/*.jar

          java: ${{ steps.properties.outputs.java_version }}

          fail-mode: warn
